### ISSUE TITLE
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it

### ISSUE THREAD

**Issue by marvinhosea** [AppsLab-KE/laravel-easy-search#5]
Unknown database type for enum not supported when creating new filter

**Comment by marvinhosea** [comment]
This is a known bug with doctrine change your column type as suggested here https://stackoverflow.com/questions/33140860/laravel-5-1-unknown-database-type-enum-requested

**Comment by AkashicSeer** [comment]
This is fun when you are reverse engineering a database with several hundred tables and many used ENUM since it is so handy.
